---
title: "Figure 2 - Gene Ontology Enrichment Analysis"
---

```{r}
source("../../Baseline/Figure S9-S10 Baseline.R")
```

```{r}

up_GO_Table <- readRDS(paste0(checkpoints_path, "up_GO_Table.rds"))

```

```{r}
sub_table <- up_GO_Table 
sub_table <- sub_table[sub_table$Count > 10, ]
sub_table <- sub_table[sub_table$Significant == "YES", ]

yaxis_order <- sub_table$Description
sub_table$Description <- factor(sub_table$Description, levels = yaxis_order)

regulation.labs <- c("Chimpanzee Upregulated Genes", "Human Upregulated Genes")
names(regulation.labs) <- c("CU", "HU")

g <- ggplot(data = sub_table, aes(x = cell_type, y = Description, 
                        color = `p.adjust`, size = Count, shape = region))      + 
  geom_point()                                                                  +
  scale_color_gradient(low = "blue", high = "red", limits = c(0, 0.05))         +
  theme_bw()                                                                    + 
  ylab("")                                                                      + 
  xlab("")                                                                      + 
  ggtitle("GO enrichment analysis") +
  facet_grid(. ~ regulation, labeller = labeller(regulation = regulation.labs)) +
  theme(axis.line = element_line(colour = "black"),
        axis.text.x=element_text(size=14, angle = 45, vjust = 1, hjust = 1),
        axis.text.y=element_text(size=12, hjust = 0),
        strip.text = element_text(face="bold", size=8))                         +
  scale_x_discrete(breaks=names(cellfullnames),
        labels=cellfullnames)


 ggsave(filename = paste0(figure_output_path, "Figure S11 - upregulated GO terms.jpg"), plot = g, device = "jpeg",
         width=10, height=9, dpi=300)
```

```{r}
sub_table <- down_GO_Table #[up_GO_Table$cell_type %in% c("Inhibit" ,"Microglia") == FALSE, ]
sub_table <- sub_table[sub_table$Count > 10, ]
sub_table <- sub_table[sub_table$Significant == "YES", ]

regulation.labs <- c("Chimpanzee Downregulated Genes", "Human Downregulated Genes")
names(regulation.labs) <- c("CD", "HD")

g <- ggplot(data = sub_table, aes(x = cell_type, y = Description, 
                        color = `p.adjust`, size = Count, shape = region)) + 
  geom_point() +
  scale_color_gradient(low = "blue", high = "red", limits = c(0, 0.05)) +
  theme_bw() +
  ylab("") + 
  xlab("") + 
  ggtitle("GO enrichment analysis") +
  facet_grid(. ~ regulation, labeller = labeller(regulation = regulation.labs)) +
  theme(axis.line = element_line(colour = "black"),
        axis.text.x=element_text(size=15, angle = 45, vjust = 0.5),
        axis.text.y=element_text(size=14, , hjust = 0),
        strip.text = element_text(face="bold", size=10))    +
  scale_x_discrete(breaks=c("Astro","Excite", "Inhibit", "Microglia"  ,"Oligo", "OPC"),
        labels=c("Astrocyte","Excitatory Neuron", "Inhibitory Neuron", "Microglia", "Oligodendrocyte", "OPC"))


 ggsave(filename = "Figures/Figure 2/GOV6/Figure 2B - GO terms - downregulation_V2.1 - FDR5V3.jpg", plot = g, device = "jpeg",
         width=10, height=5.5, dpi=300)
```

# Loading COMBINED up/down GO table data from analysis

```{r}

FDR <- c(5)
gene_count <- c(10)

for (FDR_value in FDR){
  
  for (gene_count_value in gene_count){
    
    significant_GO_table <- read_excel(paste0("Source Files/Figure 2/singificant_combined_BP_FDR", FDR_value, ".xlsx"))
    considered_GO_table  <- read_excel(paste0("Source Files/Figure 2/considered_combined_BP_FDR" , FDR_value, ".xlsx"))
    
    significant_GO_table$Significant <- "SIG"
    considered_GO_table$Significant  <- "CONS"
    all_GO_terms                     <- rbind(significant_GO_table, considered_GO_table)
    GO_table                         <- all_GO_terms[all_GO_terms$ID %in% significant_GO_table$ID, ]
    
    sub_table <- GO_table #[up_GO_Table$cell_type %in% c("Inhibit" ,"Microglia") == FALSE, ]
    
    yaxis_order           <- sub_table$Description
    yaxis_order           <- yaxis_order[!duplicated(yaxis_order)]
    sub_table$Description <- factor(sub_table$Description, levels = yaxis_order)
    
    sub_table <- sub_table[sub_table$Count > gene_count_value, ]
    sub_table <- sub_table[sub_table$Significant == "SIG", ]
    
    regulation.labs <- c("chimp", "human combined up/down regulated genes")
    names(regulation.labs) <- c("chimp", "human")
    
    g <- ggplot(data = sub_table, aes(x = cell_type, y = Description, 
                            color = `p.adjust`, size = Count, shape = region)) + 
      geom_point() +
      scale_color_gradient(low = "blue", high = "red", limits = c(0, 0.01*FDR_value)) +
      theme_bw() + 
      ylab("") + 
      xlab("") + 
      ggtitle("GO enrichment analysis") +
      facet_grid(. ~ regulation, labeller = labeller(regulation = regulation.labs)) +
      theme(axis.line = element_line(colour = "black"),
            axis.text.x=element_text(size=14, angle = 45, vjust = 1, hjust = 1),
            axis.text.y=element_text(size=24, hjust = 0),
            strip.text = element_text(face="bold", size=18))          +
      coord_flip() + 
      scale_x_discrete(breaks=c("Astro","Excite", "Inhibit", "Microglia"  ,"Oligo", "OPC"),
            labels=c("Astrocyte","Excitatory Neuron", "Inhibitory Neuron", "Microglia", "Oligodendrocyte", "OPC"))
    

     ggsave(filename = paste0("Figures/Figure 2/GOV6/combined/Figure 2A - GO terms - combined - FDR", FDR_value, "_", gene_count_value, "flipped.jpg"), plot = g, device = "jpeg",
             width=16, height=9, dpi=300)

  }
}


```


# Code from https://www.biostars.org/p/456294/
```{r}
# import package
library("ggplot2")

# create fake data
set.seed(1024) # keep reproducibility
go <- paste0("GO", sample(1000:2000, 5))
data <- data.frame("GOs" = rep(go, 2), 
                   "Condition" = rep(c("A", "B"), each = 5),
                   "GeneRatio" = 1 / sample(10, 10), 
                   "p.adjust" = 0.05 / sample(10, 10))

# plot: dot plot
ggplot(data = data, aes(x = Condition, y = GOs, 
                        color = `p.adjust`, size = GeneRatio)) + 
  geom_point() +
  scale_color_gradient(low = "red", high = "blue") +
  theme_bw() + 
  ylab("") + 
  xlab("") + 
  ggtitle("GO enrichment analysis") +
  facet_grid(. ~ supp)
```


```{r}


significant_GO_table <- read_excel("Source Files/Figure 2/singificant_combined_BP_FDR20.xlsx")
considered_GO_table  <- read_excel("Source Files/Figure 2/considered_combined_BP_FDR20.xlsx")
common_terms <- intersect(significant_GO_table[significant_GO_table$regulation == "chimp", ]$Description, significant_GO_table[significant_GO_table$regulation == "human", ]$Description)
common_GO_terms <- significant_GO_table[significant_GO_table$Description %in% common_terms, ]

common_terms <- intersect(considered_GO_table[considered_GO_table$regulation == "chimp", ]$Description, considered_GO_table[considered_GO_table$regulation == "human", ]$Description)
common_GO_terms <- considered_GO_table[considered_GO_table$Description %in% common_terms, ]



```

```{r}
human_metrics <- read_excel("Source Files/Human metrics.xlsx")

significant_GO_table <- read_excel("Source Files/Figure 2/Significant Biological Processes from DEGs - Figure 2 FDR20.xlsx")
considered_GO_table  <- read_excel("Source Files/Figure 2/Considered Biological Processes from DEGs - Figure 2 FDR20.xlsx")

significant_GO_table <- considered_GO_table[considered_GO_table$p.adjust < 0.3, ]

common_terms <- intersect(significant_GO_table[significant_GO_table$regulation == "CU", ]$Description, significant_GO_table[significant_GO_table$regulation == "HU", ]$Description)
common_GO_terms <- significant_GO_table[significant_GO_table$Description %in% common_terms, ]


shared_GO_term_descriptions <- c("response to organic cyclic compound", "positive regulation of nervous system development", "regulation of cell development", "regulation of nervous system development")
shared_GO_term_table        <- common_GO_terms[common_GO_terms$Description %in% shared_GO_term_descriptions, ]
shared_GO_term_table        <- shared_GO_term_table[shared_GO_term_table$regulation %in% c("HU", "CU"), ]
shared_GO_term_table        <- shared_GO_term_table[order(shared_GO_term_table$Description), ]
shared_GO_term_table        <- shared_GO_term_table[-c(1, 6), ]

```

```{r}
shared_GO_term_table_human_genes <- shared_GO_term_table[shared_GO_term_table$regulation == "HU", ]$geneID
split_genes <- unlist(strsplit(shared_GO_term_table_human_genes, "/"))
unique_genes_human <- unique(split_genes)
unique_genes_human

shared_GO_term_table_chimp_genes <- shared_GO_term_table[shared_GO_term_table$regulation == "CU", ]$geneID
split_genes <- unlist(strsplit(shared_GO_term_table_chimp_genes, "/"))
unique_genes_chimp <- unique(split_genes)
unique_genes_chimp

```

```{r}
subset_human_metrics <- human_metrics[human_metrics$Gene %in% c(unique_genes_chimp,
                                                                unique_genes_human), ]

subset_human_metrics <- subset_human_metrics[!duplicated(subset_human_metrics$Gene), ]
subset_human_metrics <- subset_human_metrics %>% mutate(Regulation = if_else(Gene %in% unique_genes_human, "HU", "CU"))
subset_human_metrics_to_plot <- subset_human_metrics[, c("Gene", "HAR_counts", "species_hypo_DMRs", "species_hyper_DMRs", "Regulation")]
colnames(subset_human_metrics_to_plot) <- c("Gene", "Number of", "DMRs", "species_hyper_DMRs", "Regulation")


```

```{r}
stat.test <- subset_human_metrics_to_plot            %>% 
      wilcox_test(DMRs  ~ Regulation)   %>% 
      adjust_pvalue(method = "bonferroni")           %>% 
      add_significance("p") 

stat.test <- subset_human_metrics_to_plot            %>% 
      wilcox_test(species_hyper_DMRs  ~ Regulation)  %>% 
      adjust_pvalue(method = "bonferroni")           %>% 
      add_significance("p")

stat.test <- subset_human_metrics_to_plot            %>% 
      wilcox_test(HAR_counts  ~ Regulation)          %>% 
      adjust_pvalue(method = "bonferroni")           %>% 
      add_significance("p")
```

```{r}
# Load necessary libraries
library(ggplot2)
library(dplyr)
library(tidyr)

# Assuming your data is in a dataframe named 'data'
# Reshape your data
reshaped_data <- shared_GO_term_table %>%
  separate_rows(geneID, sep = "/")    %>%
  mutate(regulation_category = ifelse(regulation == 'HU', 'HU', 'CU')) %>%
  mutate(cell_type = ifelse(cell_type == 'OPC', 'OPC', 'Oligo'))

names(reshaped_data)[names(reshaped_data) == 'geneID'] <- 'Gene'

reshaped_data <-  merge(subset_human_metrics_to_plot, reshaped_data, by = "Gene")
reshaped_data$Description_FDR <- paste0(reshaped_data$Description, " (FDR", format(round(reshaped_data$p.adjust, 2), nsmall = 2), ")")

regulation.labs <- c("Chimpanzee Upregulated Gene-vs-BP terms", "Human Upregulated Gene-vs-BP terms")
names(regulation.labs) <- c("CU", "HU")

# Create the dot plot
g <- ggplot(reshaped_data, aes(x = Description, y = Gene, color = regulation_category, size = DMRs,
                          shape = region)) +
  geom_point(aes(color=cell_type)) +
  scale_color_manual(values = c("Oligo" = "blue", "OPC" = "red")) +
  theme_bw() + 
  ylab("") + 
  xlab("") + 
  ggtitle("GO enrichment analysis") +
  facet_grid(. ~ regulation, labeller = labeller(regulation = regulation.labs))   +
  theme(axis.line = element_line(colour = "black"),
        axis.text.x=element_text(size=8.5, angle = 0, vjust = 0.8, hjust = 0.5),
        axis.text.y=element_text(size=10))       +
  labs(x = "GO Term Description", y = "Gene Name", color = "Category")            +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10), drop = FALSE)    +
  facet_grid(. ~ regulation, labeller = labeller(regulation = regulation.labs))   +
  scale_size(range = c(2,8))

 ggsave(filename = "Figures/Figure 2/V2/Functional_Convergence_V4.jpg", plot = g, device = "jpeg",
         width=7.5, height=9, dpi=300)
```


```{r}
gene_vectors <- c("PLXNA2/ROBO1/IL1RAP/GRID2/PTN/NTN1/LRRC4B", 
                  "MAP1B/FZD3/DCT/SOX8", 
                  "PLXNA2/ROBO1/SPRY4/PTN/SORL1/LRRK2/PRTG/NTRK3/NTN1", 
                  "SPP1/MAP1B/FZD3/DCT/SOX8", 
                  "PLXNA2/SLC25A12/ROBO1/IL1RAP/GRID2/PTN/SORL1/PRTG/NTRK3/NTN1/LRRC4B/JAM2", 
                  "SPP1/MAP1B/FZD3/DCT/SOX8", 
                  "ESRRG/ATP2B4/TGFBR2/GRAMD1C/SLC1A3/TRERF1/ADCY8/JAK2/CAT/GRAMD1B/SLC1A2/LRRK2/ZFP36L1/RORA/NTRK3/COLEC12/MN1/HLCS", 
                  "RXRG/P2RY1/SLIT2/CASP3/NDUFS4/SMAD5/EGFR/MSR1")

# Splitting each string by "/" and combining them into one list
split_genes <- unlist(strsplit(gene_vectors, "/"))

# Removing duplicate gene names
unique_genes <- unique(split_genes)

# Display the unique list of genes
unique_genes
```

