---
title: "Figure 2 - Visualization data generator file"
output: html_document
date: "2024-05-16"
---

```{r setup, include=FALSE}

source("../../Baseline/Figure 2 Baseline.R")

```

```{r pressure, echo=FALSE}

barplot_list_species <- list()

for (spec in species){
  
  barplot_list_study <- list()

  for (study in studies){
    
    major_type_combined_list                        <- list()
    down_regulated_genes_major_types                <- readRDS(paste0(folder_name, study, "/", study, FDR, "_original_", spec, "_DRGenes.rds"))
    up_regulated_genes_major_types                  <- readRDS(paste0(folder_name, study, "/", study, FDR, "_original_", spec, "_URGenes.rds"))
    
    for (name in names(down_regulated_genes_major_types)) {
      major_type_combined_list[[name]] <- unique(c(down_regulated_genes_major_types[[name]], 
                                                   up_regulated_genes_major_types[[name]]))
    }
    
    major_DEG_Venn                                  <- Venn(major_type_combined_list)
    major_DEG_Venn_table                            <- as.data.frame(process_region_data(major_DEG_Venn))
    
    study_wise_cell_count_table <- c()
    
    for (cellname in cellnames){
    
      # IMPORT GENE LISTS:
      
      major_cell_specific_genes                     <- major_DEG_Venn_table[major_DEG_Venn_table$name == cellname, ]$item[[1]]
      major_cells_shared_genes                      <- setdiff(major_type_combined_list[[cellname]], major_cell_specific_genes)
      study_wise_cell_count_table                   <- rbind(study_wise_cell_count_table, 
                                                             c(cellfullnames[[cellname]], "Cell type specific DEG", length(major_cell_specific_genes)),
                                                             c(cellfullnames[[cellname]], "Shared DEG",             length(major_cells_shared_genes)))
      
    }
    
    study_wise_cell_count_table           <- as.data.frame(study_wise_cell_count_table)
    colnames(study_wise_cell_count_table) <- c("Cell", "DEG_type", "Total")
    study_wise_cell_count_table$Total     <- as.numeric(study_wise_cell_count_table$Total)
    
    study_wise_cell_count_table$Cell      <- factor(study_wise_cell_count_table$Cell, levels = rev(cellfullnames_factor))
    study_wise_cell_count_table$DEG_type  <- factor(study_wise_cell_count_table$DEG_type, levels = c("Shared DEG", "Cell type specific DEG"))
    
    study_wise_cell_count_table$Sum       <- ave(study_wise_cell_count_table$Total, study_wise_cell_count_table$Cell, FUN = sum)
    study_wise_cell_count_table$Percentage<- (study_wise_cell_count_table$Total/study_wise_cell_count_table$Sum)*100
    
    barplot_list_study[[study]]           <- study_wise_cell_count_table
  
  }
  
  barplot_list_species[[spec]]            <- barplot_list_study
  
}

```

```{r}
saveRDS(barplot_list_species, "../../Visualization_data/Figure 2/barplot_list_species.rds")
```

```{r}

# Create a new workbook
wb <- createWorkbook()

# Counter for sheet names
sheet_counter <- 1

for (main_list_name in names(barplot_list_species)) {
  sublist <- barplot_list_species[[main_list_name]]
  for (sublist_name in names(sublist)) {
    sheet_name <- paste(main_list_name, sublist_name, sep = "_")
    addWorksheet(wb, sheet_name)
    writeData(wb, sheet = sheet_name, sublist[[sublist_name]])
  }
}

# Save the workbook to a file
saveWorkbook(wb, "../../Supplementary Tables/Supplementary Table 4.xlsx", overwrite = TRUE)

```

