---
title: "Khrameeva_barcode_generator_notebook"
output: html_document
date: "2023-05-27"
---

```{r setup, include=FALSE}
suppressMessages(suppressWarnings(library(Seurat)))
suppressMessages(suppressWarnings(library(hash)))
suppressMessages(suppressWarnings(library(readxl)))
suppressMessages(suppressWarnings(library(plyr)))
```

# IMPORT 

```{r cars}
metadata_file <- read_excel("author_source/metadata_file.xlsx")

traditional_cell_types <- c("Excite", "Astrocyte", "Inhibit", "Microglia", "Oligo", "OPC")
study_cell_names       <- c("Ex",  "Ast", "In",  "Mic", "Oli", "OPC")

study_name_to_local_name_hash <- hash(study_cell_names, traditional_cell_types)

```

# Add local cell type name column

```{r}
# TRADITIONAL CELL TYPES
metadata_file <- metadata_file[metadata_file$`Cell class` %in% study_cell_names,]

local_cell_name_vector <- c()
for (cell in metadata_file$`Cell class`){
  local_cell_name_vector <- c(local_cell_name_vector, 
                              study_name_to_local_name_hash[[cell]])
}
metadata_file$local_name <- local_cell_name_vector
```

```{r}
#metadata_file <- readRDS("D:/Yi/SPRING 2023/Evolution/Kanton et. al/subselected_metadata_file_with_local_names.rds")

metadata_file[metadata_file$Species == "human",]$Barcode <- paste0(metadata_file[metadata_file$Species == "human",]$Barcode, "H") 
metadata_file[metadata_file$Species == "chimp",]$Barcode <- paste0(metadata_file[metadata_file$Species == "chimp",]$Barcode, "C") 
metadata_file[metadata_file$Species == "macaque",]$Barcode <- paste0(metadata_file[metadata_file$Species == "macaque",]$Barcode, "M") 

metadata_file[metadata_file$Species == "human",]$local_name <- paste0(metadata_file[metadata_file$Species == "human",]$local_name, "_#human") 
metadata_file[metadata_file$Species == "chimp",]$local_name <- paste0(metadata_file[metadata_file$Species == "chimp",]$local_name, "_#chimp") 
metadata_file[metadata_file$Species == "macaque",]$local_name <- paste0(metadata_file[metadata_file$Species == "macaque",]$local_name, "_#macaque") 

metadata_file <- metadata_file[metadata_file$Individual != "BA1",]

#saveRDS(metadata_file, "final_metadata_file.rds")
```


```{r}

df_human_macak           <- data.frame(metadata_file[metadata_file$Species %in% c("human", "macaque"),
c("Barcode", "local_name", "Individual")])
duplicated_barcodes      <- df_human_macak$Barcode[duplicated(df_human_macak$Barcode)]
df_human_macak           <- df_human_macak[df_human_macak$Barcode %in% duplicated_barcodes == FALSE,]
rownames(df_human_macak) <- df_human_macak$Barcode
df_human_macak           <- df_human_macak[-c(1)]
df_human_macak$local_name <- as.factor(df_human_macak$local_name)
df_human_macak$Individual <- as.factor(df_human_macak$Individual)

df_human_chimp           <- data.frame(metadata_file[metadata_file$Species %in% c("human", "chimp"),
c("Barcode", "local_name", "Individual")])
duplicated_barcodes      <- df_human_chimp$Barcode[duplicated(df_human_chimp$Barcode)]
df_human_chimp           <- df_human_chimp[df_human_chimp$Barcode %in% duplicated_barcodes == FALSE,]
rownames(df_human_chimp) <- df_human_chimp$Barcode
df_human_chimp           <- df_human_chimp[-c(1)]
df_human_chimp$local_name <- as.factor(df_human_chimp$local_name)
df_human_chimp$Individual <- as.factor(df_human_chimp$Individual)

df_chimp_macak           <- data.frame(metadata_file[metadata_file$Species %in% c("macaque", "chimp"),
c("Barcode", "local_name", "Individual")])
duplicated_barcodes      <- df_chimp_macak$Barcode[duplicated(df_chimp_macak$Barcode)]
df_chimp_macak           <- df_chimp_macak[df_chimp_macak$Barcode %in% duplicated_barcodes == FALSE,]
rownames(df_chimp_macak) <- df_chimp_macak$Barcode
df_chimp_macak           <- df_chimp_macak[-c(1)]
df_chimp_macak$local_name <- as.factor(df_chimp_macak$local_name)
df_chimp_macak$Individual <- as.factor(df_chimp_macak$Individual)

sample_to_gender <- hash(c(3, "CHD2", "MI1", "MG2", "MH1", "HC1", "HG1", "HE1"),
                         c("M", "F"   ,  "M" , "M"  , "M"  , "F"  , "M"  , "M"))

sample_to_age <- hash(c(3, "CHD2", "MI1", "MG2", "MH1", "HC1", "HG1", "HE1"),
                      c(round(2.06871*12 - 2.30729, 1) ,  round(2.06871*45 - 2.30729, 1),
                        round(3.05864*9 + 0.47236, 1)  ,  round(3.05864*7 + 0.47236, 1) , round(3.05864*9 + 0.47236, 1),  
                        34                             ,                           54   ,  17))


```

# COUNT CELL TYPES USEING COUNT FUNCTION

You can also embed plots, for example:

```{r pressure, echo=FALSE}
df_chimp_macak_sex_vector <- c()
df_human_chimp_sex_vector <- c()
df_human_macak_sex_vector <- c()

df_chimp_macak_age_vector <- c()
df_human_chimp_age_vector <- c()
df_human_macak_age_vector <- c()

for (sample_id in df_chimp_macak$Individual){
  df_chimp_macak_sex_vector <- c(df_chimp_macak_sex_vector, sample_to_gender[[sample_id]])
  df_chimp_macak_age_vector <- c(df_chimp_macak_age_vector, sample_to_age[[sample_id]])
}

for (sample_id in df_human_chimp$Individual){
  df_human_chimp_sex_vector <- c(df_human_chimp_sex_vector, sample_to_gender[[sample_id]])
  df_human_chimp_age_vector <- c(df_human_chimp_age_vector, sample_to_age[[sample_id]])
}

for (sample_id in df_human_macak$Individual){
  df_human_macak_sex_vector <- c(df_human_macak_sex_vector, sample_to_gender[[sample_id]])
  df_human_macak_age_vector <- c(df_human_macak_age_vector, sample_to_age[[sample_id]])
}

df_human_chimp$human_age <- df_human_chimp_age_vector
df_human_chimp$sex       <- as.factor(df_human_chimp_sex_vector)

df_chimp_macak$human_age <- df_chimp_macak_age_vector
df_chimp_macak$sex       <- as.factor(df_chimp_macak_sex_vector)

df_human_macak$human_age <- df_human_macak_age_vector
df_human_macak$sex       <- as.factor(df_human_macak_sex_vector)

colnames(df_chimp_macak)         <- c("trad", "sample_id", "human_age",  "sex")
colnames(df_human_chimp)         <- c("trad", "sample_id", "human_age",  "sex")
colnames(df_human_macak)         <- c("trad", "sample_id", "human_age",  "sex")

```

# SAVE METADATA FILES

```{r}
saveRDS(df_human_macak, "pairwise_metadata_files/df_human_macak.rds")
saveRDS(df_human_chimp, "pairwise_metadata_files/df_human_chimp.rds")
saveRDS(df_chimp_macak, "pairwise_metadata_files/df_chimp_macak.rds")
```

