---
title: "Proportion Change Calculator"
output: 
editor_options: 
  chunk_output_type: inline
---

```{r}

source("../../Baseline/Figure S1-S3 Baseline.R")

```


```{r}

for (study in study_results){
  
  cell_names                    <- c()
  
  study_cell_count_files        <- cell_counts_files[tstrsplit(cell_counts_files, "_")[[1]] %in% study]
  
  chimp_cell_counts             <- readRDS(paste0(cell_counts_path, study_cell_count_files[1]))
  human_cell_counts             <- readRDS(paste0(cell_counts_path, study_cell_count_files[2]))
  macaque_cell_counts           <- readRDS(paste0(cell_counts_path, study_cell_count_files[3]))
  
  p     <- list()
  count <- 1
  
  gene_proportion_table         <- read_excel(paste0(gene_table_path, study, "_Figure_S1_to_S3_gene_table.xlsx"))
  
  
  for (cell_type in cell_types){
    

    
    grob1 <- grobTree(textGrob(paste0("n(Human ", cell_full_names_hash[[cell_type]], " cells) :", human_cell_counts[[cell_type]]), 
                              x=0.05,  y=0.95, hjust=0, gp=gpar(col="black", fontsize=8, fontface="bold")))
    
    grob2 <- grobTree(textGrob(paste0("n(Chimp ", cell_full_names_hash[[cell_type]], " cells)  :", chimp_cell_counts[[cell_type]]), 
                              x=0.05,  y=0.90, hjust=0, gp=gpar(col="black", fontsize=8, fontface="bold")))
    
    grob4 <- grobTree(textGrob(paste0("n(Macaque ", cell_full_names_hash[[cell_type]], " cells)  :", macaque_cell_counts[[cell_type]]), 
                              x=0.05,  y=0.85, hjust=0, gp=gpar(col="black", fontsize=8, fontface="bold")))
    
    grob3 <- grobTree(textGrob(paste0("n(Considered non-silent genes) :", gene_proportion_table[gene_proportion_table$...1 == cell_type, "Considered Genes"]), 
                              x=0.05,  y=0.80, hjust=0, gp=gpar(col="black", fontsize=8, fontface="bold")))
    
    
    print(cell_type)
    counts <- data.frame(rbind(c(as.numeric(gene_proportion_table[gene_proportion_table$...1 == cell_type, "Chimp.Specific.DOWN.Proportion"]), "Chimp", "DOWN"),
                               c(as.numeric(gene_proportion_table[gene_proportion_table$...1 == cell_type, "Human.Specific.DOWN.Proportion"]), "Human", "DOWN"),
                               c(as.numeric(gene_proportion_table[gene_proportion_table$...1 == cell_type, "Chimp.Specific.UP.Proportion"]),   "Chimp", "UP"  ),
                               c(as.numeric(gene_proportion_table[gene_proportion_table$...1 == cell_type, "Human.Specific.UP.Proportion"]),   "Human", "UP"  )))
  
    colnames(counts) <- c("Number", "Species", "Regulation")
    print(counts)
    counts$Number <- as.numeric(counts$Number)

    p[[count]] <- ggplot(counts, aes(x = factor(Species, level = c("Human", "Chimp")), Number, fill = Regulation))           +
                  geom_bar(stat="identity", position = "dodge")                                                              +
                  labs(title=cell_full_names_hash[[cell_type]])        + theme_classic()                                     +
                  ylim(c(0, 10.0))                                                                                           + 
                  scale_fill_manual(values=list("darkblue", "red"))                                                          +
                  geom_text(aes(label=Number, y = Number), position=position_dodge(width=0.9), vjust=-1.0, size=5)           + 
                  labs(y= "DEG proportion", x = NULL)   + theme(legend.position = "none")                                   + 
                  theme(axis.text = element_text(size = 15))  + annotation_custom(grob1) + annotation_custom(grob2) + annotation_custom(grob4) + annotation_custom(grob3) 
        
    count <- count + 1
    
  }

  g <- ggarrange(plotlist = p, nrow=2, ncol = 3, common.legend = TRUE, legend="bottom")
  
  g <- annotate_figure(g, top = text_grob(paste0("Percentage of species-specific DE genes in ", name_to_region_hash[[study]], " (", study," et. al.), FDR = ", FDR, " \n"),
                                          color = "black", face = "bold", size = 20, y = 0.5),
                          bottom = text_grob(paste0(" Number of Genes : ", study_to_gene_number_hash[[study]], " \n Number of human samples : ", study_to_human_replicate_number_hash[[study]],
                                                                                                               " \n Number of chimp samples : ", study_to_chimp_replicate_number_hash[[study]]), 
                                          color = "black", hjust = 0, x = 0.65, y = 1, size = 15))

  # ggsave(filename = paste0(figure_output_path, study, "FDR", 100*FDR, "_Supplementary_Figure.jpg"), plot = g, device = "jpeg",
  #        width=14.4, height=9, dpi=300)
}
```

