---
title: "Proportion Change Calculator"
output: 
editor_options: 
  chunk_output_type: inline
---

```{r}

source("../../Baseline/Figure S1-S3 Baseline.R")

```


```{r}
all_counts <- c()

for (study in study_results){
  
  cell_names                    <- c()
  
  study_cell_count_files        <- cell_counts_files[tstrsplit(cell_counts_files, "_")[[1]] %in% study]
  
  chimp_cell_counts             <- readRDS(paste0(cell_counts_path, study_cell_count_files[1]))
  human_cell_counts             <- readRDS(paste0(cell_counts_path, study_cell_count_files[2]))
  macaque_cell_counts           <- readRDS(paste0(cell_counts_path, study_cell_count_files[3]))
  
  p     <- list()
  count <- 1
  
  gene_proportion_table         <- read_excel(paste0(gene_table_path, study, "_Figure_S1_to_S3_gene_table.xlsx"))
  
  all_cell_counts               <- c()
  
  for (cell_type in cell_types){
    

    
    grob1 <- grobTree(textGrob(paste0("n(Human ", cell_full_names_hash[[cell_type]], " cells) :", human_cell_counts[[cell_type]]), 
                              x=0.05,  y=0.95, hjust=0, gp=gpar(col="black", fontsize=8, fontface="bold")))
    
    grob2 <- grobTree(textGrob(paste0("n(Chimp ", cell_full_names_hash[[cell_type]], " cells)  :", chimp_cell_counts[[cell_type]]), 
                              x=0.05,  y=0.90, hjust=0, gp=gpar(col="black", fontsize=8, fontface="bold")))
    
    grob4 <- grobTree(textGrob(paste0("n(Macaque ", cell_full_names_hash[[cell_type]], " cells)  :", macaque_cell_counts[[cell_type]]), 
                              x=0.05,  y=0.85, hjust=0, gp=gpar(col="black", fontsize=8, fontface="bold")))
    
    grob3 <- grobTree(textGrob(paste0("n(Considered non-silent genes) :", gene_proportion_table[gene_proportion_table$...1 == cell_type, "Considered Genes"]), 
                              x=0.05,  y=0.80, hjust=0, gp=gpar(col="black", fontsize=8, fontface="bold")))
    
    
    print(cell_type)
    counts <- data.frame(rbind(c(-as.numeric(gene_proportion_table[gene_proportion_table$...1 == cell_type, "Chimp.Specific.DOWN.Proportion"]), "Chimp", "DOWN"),
                               c(-as.numeric(gene_proportion_table[gene_proportion_table$...1 == cell_type, "Human.Specific.DOWN.Proportion"]), "Human", "DOWN"),
                               c(as.numeric(gene_proportion_table[gene_proportion_table$...1 == cell_type, "Chimp.Specific.UP.Proportion"]),   "Chimp", "UP"  ),
                               c(as.numeric(gene_proportion_table[gene_proportion_table$...1 == cell_type, "Human.Specific.UP.Proportion"]),   "Human", "UP"  )))
  
    colnames(counts) <- c("Number", "Species", "Regulation")
    print(counts)
    counts$Number <- as.numeric(counts$Number)
    counts$Cell   <- cell_type
    counts$Study  <- study
    
    all_cell_counts <- rbind(all_cell_counts, counts)


    count <- count + 1
    
  }
  
  all_counts <- rbind(all_counts, all_cell_counts)

}


```

```{r}

all_counts$Spec_Reg   <- paste0(all_counts$Species, "-", all_counts$Regulation)
all_counts$Spec_Reg   <- factor(all_counts$Spec_Reg, levels = c("Human-UP", "Chimp-UP", "Human-DOWN", "Chimp-DOWN"))
all_counts$Cell       <- factor(all_counts$Cell, levels = c("Excite",    "Inhibit",  "Astro",  "Microglia", "Oligo", "OPC"))
all_counts$Study      <- factor(all_counts$Study)

```

```{r}
saveRDS(all_counts, "../../Visualization_data/Figure S1-S3/combined_S123.rds")
```

