---
title: "Figure 2 - Gene Ontology Enrichment Analysis"
---

```{r}
source("../../Baseline/Figure S11-S14 Baseline.R")
```

```{r}

sub_table <- readRDS(paste0(checkpoints_path, "combined_GO_Table.rds"))

```

```{r}


g <-  ggplot(data = sub_table, aes(x = cell_type, y = Description, 
                        color = `p.adjust`, size = Count, shape = region))            + 
      geom_point()                                                                    +
      scale_color_gradient(low = "blue", high = "red", limits = c(0, 0.01*FDR_value)) +
      theme_bw()                                                                      + 
      ylab("")                                                                        + 
      xlab("")                                                                        + 
      ggtitle("GO enrichment analysis")                                               +
      facet_grid(. ~ regulation, labeller = labeller(regulation = regulation.labs))   +
      theme(axis.line = element_line(colour = "black"),
            axis.text.x=element_text(size=14, angle = 45, vjust = 1, hjust = 1),
            axis.text.y=element_text(size=24, hjust = 0),
            strip.text = element_text(face="bold", size=18))                          +
      coord_flip()                                                                    + 
      scale_x_discrete(breaks=names(cellfullnames),
            labels=cellfullnames)

ggsave(filename = paste0(figure_output_path, "Figure S14 - combined regulation GO terms.jpg"), plot = g, device = "jpeg",
             width=16, height=9, dpi=300)
 
```

