---
title: "Shaojie_barcode_generator_notebook"
output: html_document
date: "2023-05-27"
---

```{r setup, include=FALSE}
suppressMessages(suppressWarnings(library(Seurat)))
suppressMessages(suppressWarnings(library(hash)))
suppressMessages(suppressWarnings(library(plyr)))
suppressMessages(suppressWarnings(library(readxl)))
suppressMessages(suppressWarnings(library(dplyr)))

```

# IMPORT 

```{r cars}
human_metadata_file <- as.data.frame(read_excel("author_source/Human_metadata.xlsx"))
chimp_metadata_file <- as.data.frame(read_excel("author_source/Chimp_metadata.xlsx"))
macaque_metadata_file <- as.data.frame(read_excel("author_source/Rhesus_metadata.xlsx"))
individual_metadata <- read_excel("author_source/individual_metadata.xlsx")
gender_hash <- hash(c("Male", "Female"), c("M", "F"))
#source("author_source/cellname_map_function.R")
```

```{r}
common_name <- list("Oligo",      "OPC",        "Astro",      "Microglia",  "Excite",      "Excite",        "Excite",    "Excite",      "Inhibit",      "Inhibit", "Inhibit", "Inhibit",     "Inhibit", "Inhibit",        "Inhibit",      "Inhibit", "Inhibit",  "Excite",      "Excite",      "Excite",      "Excite", "Excite")

paper_name <- c("Oligo",      "OPC",        "Astro",      "Micro-PVM",  "L6 CT",      "L6b",        "L5/6 NP",    "L5 ET",      "Lamp5",      "Vip", "Pax6",       "Sncg",     "Lamp5_Lhx6", "Sst",        "Pvalb",      "Chandelier", "Sst Chodl",  "L5 IT",      "L4 IT",      "L6 IT",      "L6 IT Car3", "L2/3 IT")

names(common_name) <- paper_name

sample_to_age        <- individual_metadata$Age_yrs
names(sample_to_age) <- individual_metadata$ID

sample_to_gender <- individual_metadata$Sex
names(sample_to_gender) <- individual_metadata$ID
```

```{r}
human_metadata_file <- human_metadata_file[human_metadata_file$confirmed_subclass %in% paper_name,]
common_names_human  <- c()
age_human           <- c()
gender_human        <- c()
for (i in c(1:length(human_metadata_file$confirmed_subclass))){
  common_names_human  <- c(common_names_human, common_name[[human_metadata_file$confirmed_subclass[i]]])
  age_human           <- c(age_human, sample_to_age[[human_metadata_file$donor[i]]])
  gender_human        <- c(gender_human, sample_to_gender[[human_metadata_file$donor[i]]])
}

human_metadata_file$common_name <- common_names_human
human_metadata_file$human_age   <- age_human
human_metadata_file$sex         <- gender_human

chimp_metadata_file <- chimp_metadata_file[chimp_metadata_file$confirmed_subclass %in% paper_name,]
common_names_chimp  <- c()
age_chimp           <- c()
gender_chimp        <- c()
for (i in c(1:length(chimp_metadata_file$confirmed_subclass))){
  common_names_chimp  <- c(common_names_chimp, common_name[[chimp_metadata_file$confirmed_subclass[i]]])
  age_chimp           <- c(age_chimp, round(2.06871*sample_to_age[[chimp_metadata_file$donor[i]]] - 2.30729, 1))
  gender_chimp        <- c(gender_chimp, sample_to_gender[[chimp_metadata_file$donor[i]]])
}

chimp_metadata_file$common_name <- common_names_chimp
chimp_metadata_file$human_age   <- age_chimp
chimp_metadata_file$sex         <- gender_chimp

macaque_metadata_file <- macaque_metadata_file[macaque_metadata_file$confirmed_subclass %in% paper_name,]
common_names_macaque  <- c()
age_macaque           <- c()
gender_macaque        <- c()
for (i in c(1:length(macaque_metadata_file$confirmed_subclass))){
  common_names_macaque  <- c(common_names_macaque, common_name[[macaque_metadata_file$confirmed_subclass[i]]])
  age_macaque           <- c(age_macaque, round(3.05864*sample_to_age[[macaque_metadata_file$donor[i]]] + 0.47236, 1))
  gender_macaque        <- c(gender_macaque, sample_to_gender[[macaque_metadata_file$donor[i]]])
}

macaque_metadata_file$common_name <- common_names_macaque
macaque_metadata_file$human_age   <- age_macaque
macaque_metadata_file$sex         <- gender_macaque
```

```{r}
human_metadata_file$common_name   <- paste0(human_metadata_file$common_name, "_#human")
chimp_metadata_file$common_name   <- paste0(chimp_metadata_file$common_name, "_#chimp")
macaque_metadata_file$common_name <- paste0(macaque_metadata_file$common_name, "_#macaque")
```


```{r}
# saveRDS(human_metadata_file, "human_metadata_file.rds")
# saveRDS(chimp_metadata_file, "chimp_metadata_file.rds")
# saveRDS(macaque_metadata_file, "macaque_metadata_file.rds")
# 
human_metadata_file  <- readRDS("human_metadata_file.rds")
chimp_metadata_file   <- readRDS("chimp_metadata_file.rds")
macaque_metadata_file <- readRDS("macaque_metadata_file.rds")



human_metadata_file   <- human_metadata_file[, c("sample_id", "common_name", "donor", "human_age", "sex")]
chimp_metadata_file   <- chimp_metadata_file[, c("sample_id", "common_name", "donor", "human_age", "sex")]
macaque_metadata_file <- macaque_metadata_file[, c("sample_id", "common_name", "donor","human_age", "sex")]

rownames(human_metadata_file)   <- human_metadata_file$sample_id
rownames(chimp_metadata_file)   <- chimp_metadata_file$sample_id
rownames(macaque_metadata_file) <- macaque_metadata_file$sample_id


human_metadata_file   <- human_metadata_file[, -c(1)]
chimp_metadata_file   <- chimp_metadata_file[, -c(1)]
macaque_metadata_file <- macaque_metadata_file[, -c(1)]


```

```{r}
rownames(human_metadata_file)   <- paste0(rownames(human_metadata_file), "H")
rownames(chimp_metadata_file)   <- paste0(rownames(chimp_metadata_file), "C")
rownames(macaque_metadata_file) <- paste0(rownames(macaque_metadata_file), "M")
```


```{r}
df_human_macak <- rbind(human_metadata_file, macaque_metadata_file)
df_human_chimp <- rbind(human_metadata_file, chimp_metadata_file)
df_chimp_macak <- rbind(chimp_metadata_file, macaque_metadata_file)

```


```{r}

df_human_macak$common_name          <- as.factor(df_human_macak$common_name)
df_human_chimp$common_name          <- as.factor(df_human_chimp$common_name)
df_chimp_macak$common_name          <- as.factor(df_chimp_macak$common_name)

df_human_macak$donor          <- as.factor(df_human_macak$donor)
df_human_chimp$donor          <- as.factor(df_human_chimp$donor)
df_chimp_macak$donor          <- as.factor(df_chimp_macak$donor)

# df_human_macak$human_age          <- as.factor(df_human_macak$human_age)
# df_human_chimp$human_age          <- as.factor(df_human_chimp$human_age)
# df_chimp_macak$human_age          <- as.factor(df_chimp_macak$human_age)

df_human_macak$sex          <- as.factor(df_human_macak$sex)
df_human_chimp$sex          <- as.factor(df_human_chimp$sex)
df_chimp_macak$sex          <- as.factor(df_chimp_macak$sex)

colnames(df_chimp_macak)         <- c("trad", "sample_id",  "human_age",  "sex")
colnames(df_human_chimp)         <- c("trad", "sample_id",  "human_age",  "sex")
colnames(df_human_macak)         <- c("trad", "sample_id",  "human_age",  "sex")




```

# SAVE METADATA FILES

```{r}
saveRDS(df_human_macak, "macaque_pairwise_metadata/df_human_macak.rds")
saveRDS(df_human_chimp, "macaque_pairwise_metadata/df_human_chimp.rds")
saveRDS(df_chimp_macak, "macaque_pairwise_metadata/df_chimp_macak.rds")
```

