---
title: "Khrameeva_barcode_generator_notebook"
output: html_document
date: "2023-05-27"
---

```{r setup, include=FALSE}
suppressMessages(suppressWarnings(library(Seurat)))
suppressMessages(suppressWarnings(library(hash)))
suppressMessages(suppressWarnings(library(plyr)))
suppressMessages(suppressWarnings(library(data.table)))
```

# IMPORT 

```{r cars}
Khrameeva_metadata_humans   <- readRDS("D:/Yi/Evolution Paper/Metadata generator files/Khrameeva et. al/author_source/Khrameeva_metadata_humans_withMicroglia.rds")
Khrameeva_metadata_chimps   <- readRDS("D:/Yi/Evolution Paper/Metadata generator files/Khrameeva et. al/author_source/Khrameeva_metadata_chimp_withMicroglia.rds")
Khrameeva_metadata_macauque <- readRDS("D:/Yi/Evolution Paper/Metadata generator files/Khrameeva et. al/author_source/Khrameeva_metadata_macauque_withMicroglia.rds")

Khrameeva_metadata_humans$trad   <- paste0(Khrameeva_metadata_humans$trad, "_#human")
Khrameeva_metadata_chimps$trad   <- paste0(Khrameeva_metadata_chimps$trad, "_#chimp")
Khrameeva_metadata_macauque$trad <- paste0(Khrameeva_metadata_macauque$trad, "_#macaque")

Khrameeva_metadata_humans$sample_id   <- paste0("h", Khrameeva_metadata_humans$sample_id)
Khrameeva_metadata_chimps$sample_id   <- paste0("c", Khrameeva_metadata_chimps$sample_id)
Khrameeva_metadata_macauque$sample_id <- paste0("m", Khrameeva_metadata_macauque$sample_id)

rownames(Khrameeva_metadata_humans)   <- paste0(rownames(Khrameeva_metadata_humans)  , "H")
rownames(Khrameeva_metadata_chimps)   <- paste0(rownames(Khrameeva_metadata_chimps)  , "C")
rownames(Khrameeva_metadata_macauque) <- paste0(rownames(Khrameeva_metadata_macauque), "M")

chimp_sample_to_gender <- hash(c(1, 2, 3), c("M", "F", "F"))
macak_sample_to_gender <- hash(c(1, 2, 3), c("M", "M", "F"))
human_sample_to_gender <- hash(c(1, 2, 3), c("M", "F", "F"))

# HUMANIZED AGES

chimp_sample_to_age <- hash(c(1, 2, 3), round(2.06871*c(28, 31, 45) - 2.30729, 1))
macak_sample_to_age <- hash(c(1, 2, 3), round(3.05864*c(8.5, 10, 11) + 0.47236, 1))
human_sample_to_age <- hash(c(1, 2, 3), c(62, 61, 23))

```

# COUNT CELL TYPES USEING COUNT FUNCTION

You can also embed plots, for example:

```{r pressure, echo=FALSE}
df_chimp_sex_vector <- c()
df_human_sex_vector <- c()
df_macak_sex_vector <- c()

df_chimp_age_vector <- c()
df_human_age_vector <- c()
df_macak_age_vector <- c()

for (sample_id in tstrsplit(Khrameeva_metadata_chimps$sample_id, "c")[[2]]){
  df_chimp_sex_vector <- c(df_chimp_sex_vector, chimp_sample_to_gender[[sample_id]])
  df_chimp_age_vector <- c(df_chimp_age_vector, chimp_sample_to_age[[sample_id]])
}

for (sample_id in tstrsplit(Khrameeva_metadata_humans$sample_id, "h")[[2]]){
  df_human_sex_vector <- c(df_human_sex_vector, human_sample_to_gender[[sample_id]])
  df_human_age_vector <- c(df_human_age_vector, human_sample_to_age[[sample_id]])
}

for (sample_id in tstrsplit(Khrameeva_metadata_macauque$sample_id, "m")[[2]]){
  df_macak_sex_vector <- c(df_macak_sex_vector, macak_sample_to_gender[[sample_id]])
  df_macak_age_vector <- c(df_macak_age_vector, macak_sample_to_age[[sample_id]])
}

Khrameeva_metadata_chimps$human_age <- df_chimp_sex_vector
Khrameeva_metadata_chimps$sex       <- df_chimp_age_vector

Khrameeva_metadata_humans$human_age <- df_human_sex_vector
Khrameeva_metadata_humans$sex       <- df_human_age_vector

Khrameeva_metadata_macauque$human_age <- df_macak_sex_vector
Khrameeva_metadata_macauque$sex       <- df_macak_age_vector



```

# COMBINE METADATA FILES PAIRWISE

```{r}
df_human_macak <- rbind(Khrameeva_metadata_humans, Khrameeva_metadata_macauque)
df_human_chimp <- rbind(Khrameeva_metadata_humans, Khrameeva_metadata_chimps)
df_chimp_macak <- rbind(Khrameeva_metadata_chimps, Khrameeva_metadata_macauque)


colnames(df_chimp_macak)         <- c("trad", "sample_id",  "sex", "human_age")
colnames(df_human_chimp)         <- c("trad", "sample_id",  "sex", "human_age")
colnames(df_human_macak)         <- c("trad", "sample_id",  "sex", "human_age")

df_chimp_macak$trad <- as.factor(df_chimp_macak$trad)
df_human_chimp$trad <- as.factor(df_human_chimp$trad)
df_human_macak$trad <- as.factor(df_human_macak$trad)

df_chimp_macak$sample_id <- as.factor(df_chimp_macak$sample_id)
df_human_chimp$sample_id <- as.factor(df_human_chimp$sample_id)
df_human_macak$sample_id <- as.factor(df_human_macak$sample_id)


df_human_macak$human_age          <- df_human_macak$human_age
df_human_chimp$human_age          <- df_human_chimp$human_age
df_chimp_macak$human_age          <- df_chimp_macak$human_age

df_human_macak$sex          <- as.factor(df_human_macak$sex)
df_human_chimp$sex          <- as.factor(df_human_chimp$sex)
df_chimp_macak$sex          <- as.factor(df_chimp_macak$sex)

```

# SAVE METADATA FILES

```{r}
saveRDS(df_human_macak, "pairwise_metadata_files/df_human_macak.rds")
saveRDS(df_human_chimp, "pairwise_metadata_files/df_human_chimp.rds")
saveRDS(df_chimp_macak, "pairwise_metadata_files/df_chimp_macak.rds")
```

