---
title: "Upset plot"

---

```{r}

source("../../Baseline/Figure S8-S9 Baseline.R")

```

```{r}

count           <- 1

m_list_human    <- list()
study_comb      <- list()
for (study in study_results[c(1, 6)]){
  
  human_down_regulated                     <- readRDS(paste0(folder_name, study, "/", study, FDR, "_original_human_DRGenes.rds"))
  
  names(human_down_regulated)              <- cell_full_names
  bool_human_down_regulated                <- list_to_matrix(human_down_regulated)
  comb_human_down_regulated                <- make_comb_mat(bool_human_down_regulated, mode = "intersect")
  
  human_up_regulated                     <- readRDS(paste0(folder_name, study, "/", study, FDR, "_original_human_URGenes.rds"))
  
  names(human_up_regulated)              <- cell_full_names
  bool_human_up_regulated                <- list_to_matrix(human_up_regulated)
  comb_human_up_regulated                <- make_comb_mat(bool_human_up_regulated, mode = "intersect")
  
  up_and_down_regulated_gene_list        <- list()
  
  for (cell in cell_full_names){
    
    up_and_down_regulated_gene_list[[cell]] <- c(human_down_regulated[[cell]],
                                                 human_up_regulated[[cell]])
    
  }
  
  up_and_down_regulated_matrix            <- list_to_matrix(up_and_down_regulated_gene_list)
  comb_up_and_down_regulated_gene_list    <- make_comb_mat(up_and_down_regulated_matrix, mode = "intersect")
  
  
  study_comb[[count]] <- comb_up_and_down_regulated_gene_list
  
  count <- count + 1
  
}

m_list_human <- normalize_comb_mat(list(study_comb[[1]], study_comb[[2]]))
```

```{r}

count           <- 1

m_list_chimp    <- list()
study_comb      <- list()
for (study in study_results[c(1, 6)]){
  
  human_down_regulated                     <- readRDS(paste0(folder_name, study, "/", study, FDR, "_original_chimp_DRGenes.rds"))
  
  names(human_down_regulated)              <- cell_full_names
  bool_human_down_regulated                <- list_to_matrix(human_down_regulated)
  comb_human_down_regulated                <- make_comb_mat(bool_human_down_regulated, mode = "intersect")
  
  human_up_regulated                     <- readRDS(paste0(folder_name, study, "/", study, FDR, "_original_chimp_URGenes.rds"))
  
  names(human_up_regulated)              <- cell_full_names
  bool_human_up_regulated                <- list_to_matrix(human_up_regulated)
  comb_human_up_regulated                <- make_comb_mat(bool_human_up_regulated, mode = "intersect")
  
  up_and_down_regulated_gene_list        <- list()
  
  for (cell in cell_full_names){
    
    up_and_down_regulated_gene_list[[cell]] <- c(human_down_regulated[[cell]],
                                                 human_up_regulated[[cell]])
    
  }
  
  up_and_down_regulated_matrix            <- list_to_matrix(up_and_down_regulated_gene_list)
  comb_up_and_down_regulated_gene_list    <- make_comb_mat(up_and_down_regulated_matrix, mode = "intersect")
  
  
  study_comb[[count]] <- comb_up_and_down_regulated_gene_list
  
  count <- count + 1
  
}


m_list_chimp <- normalize_comb_mat(list(study_comb[[1]], study_comb[[2]]))
```

```{r}

saveRDS(m_list_human, paste0(checkpoints_path, "human_upset_plot_data.rds"))
saveRDS(m_list_chimp, paste0(checkpoints_path, "chimp_upset_plot_data.rds"))

```

