---
title: "Figure 2 - Cell specific and shared DEGs for humans and chimpanzees"
---

```{r}

source("../../Baseline/Figure 2 Baseline.R")

```

```{r}


all_barplots <- readRDS("../../Visualization_data/Figure 2/barplot_list_species.rds")

for (spec in species){
 
  count <- 1
  p     <- list()

  for(study in studies){

    barplot <- all_barplots[[spec]][[study]]
    
    p[[count]] <- ggplot(barplot, aes(x=Cell, y=Total , fill=DEG_type ))                         +
                  geom_bar(position="stack", stat="identity",  color = "black", aes(fill=DEG_type ))  +
                  theme_bw() +
                  theme(axis.text.x  = element_text(size=18, angle = 0, vjust = 1, hjust = 0.5),
                        axis.text.y  = element_blank(),
                        axis.title.x = element_text(size=20),
                        axis.title.y = element_text(size=20),
                        legend.title = element_text(size=15),
                        legend.text  = element_text(size=15), 
                        legend.position = "bottom")                                                          +
                  ylim(0, 800)                                                                               +
                  scale_fill_manual(values=colour_list[[spec]])                                              +
                  scale_x_discrete(labels = function(x) str_wrap(x, width = 10), drop = FALSE)               +
                  ylab("")                                                                                   +
                  xlab("")                                                                                   +
                  guides(fill=guide_legend(title="Type of Gene", nrow = 2))                                  +
                  coord_flip()
                  
     count <- count + 1

  }
  
  cell_plot_arrange <- ggarrange(plotlist = p, nrow=1, ncol = 2, common.legend = TRUE, legend="bottom")

  ggsave(filename = paste0(figure_path, "/Figure 2 - ", spec, " Cell specific and shared DEG split.jpg"), plot = cell_plot_arrange, device = "jpeg",
           width=14, height=7, dpi=300)
  
}
```
