---
title: "Figure 1 - stacked Gene Proportions"
---

# IMPORT RELEVANT LIBARIES

```{r}

source("../../Baseline/Figure S17-18 Baseline.R")

```


```{r}
cell_count_studies_PCC   <- read_excel(paste0(subtype_folder_name, "Cell counts from both studies.xlsx"), sheet = "PCC")
cell_count_studies_dlPFC <- read_excel(paste0(subtype_folder_name, "Cell counts from both studies.xlsx"), sheet = "dlPFC")
```


```{r}

p     <- list()
count <- 1

Neuron_wise_df <- c()

for (Neuron_type in c("Excite", "Inhibit")){

  study_wise_subtype_df <- c()
  for (study in studies){

    gene_proportion_table       <- read_excel(paste0(subtype_folder_name, study, "/", study, "_gene_table_prefiltering.xlsx"))
    local_cell_names            <- gene_proportion_table$...1
    cell_name_hash              <- readRDS(paste0("../../common_support_files/", study, "_cell_name_hash.rds"))
    cell_name_list              <- as.list(cell_name_hash)

    neuron_selector             <- names(cell_name_list[cell_name_list==Neuron_type])
    
    subtype_genes_UR_Human         <- readRDS(paste0(subtype_folder_name, study, "/", study, "0.05_original_HUMAN_URGenes.rds"))
    subtype_genes_DR_Human         <- readRDS(paste0(subtype_folder_name, study, "/", study, "0.05_original_HUMAN_DRGenes.rds"))
    subtype_genes_UR_Chimp         <- readRDS(paste0(subtype_folder_name, study, "/", study, "0.05_original_CHIMP_URGenes.rds"))
    subtype_genes_DR_Chimp         <- readRDS(paste0(subtype_folder_name, study, "/", study, "0.05_original_CHIMP_DRGenes.rds"))

    majortype_genes_UR_Human       <- readRDS(paste0(major_folder_name, study, "/", study, "0.05_original_HUMAN_URGenes.rds"))
    majortype_genes_DR_Human       <- readRDS(paste0(major_folder_name, study, "/", study, "0.05_original_HUMAN_DRGenes.rds"))
    majortype_genes_UR_Chimp       <- readRDS(paste0(major_folder_name, study, "/", study, "0.05_original_CHIMP_URGenes.rds"))
    majortype_genes_DR_Chimp       <- readRDS(paste0(major_folder_name, study, "/", study, "0.05_original_CHIMP_DRGenes.rds"))

    sub_type_overlap_list_UR_HUMAN <- c()
    sub_type_overlap_list_DR_HUMAN <- c()
    sub_type_overlap_list_UR_CHIMP <- c()
    sub_type_overlap_list_DR_CHIMP <- c()

    all_counts <- c()

    for (cell in neuron_selector){

      sub_type_overlap_list_UR_HUMAN <- rbind(sub_type_overlap_list_UR_HUMAN,
                                              c(as.numeric(round(length(intersect(subtype_genes_UR_Human[[cell]], majortype_genes_UR_Human[[cell_name_list[[cell]]]])), 2)),
                                              cell, cell_name_list[[cell]], "UP", "Human"))

      sub_type_overlap_list_DR_HUMAN <- rbind(sub_type_overlap_list_DR_HUMAN,
                                              c(as.numeric(-round(length(intersect(subtype_genes_DR_Human[[cell]], majortype_genes_DR_Human[[cell_name_list[[cell]]]])), 2)),
                                              cell, cell_name_list[[cell]], "DOWN", "Human"))

      sub_type_overlap_list_UR_CHIMP <- rbind(sub_type_overlap_list_UR_CHIMP,
                                              c(as.numeric(round(length(intersect(subtype_genes_UR_Chimp[[cell]], majortype_genes_UR_Chimp[[cell_name_list[[cell]]]])), 2)),
                                              cell, cell_name_list[[cell]], "UP", "Chimp"))

      sub_type_overlap_list_DR_CHIMP <- rbind(sub_type_overlap_list_DR_CHIMP,
                                              c(as.numeric(-round(length(intersect(subtype_genes_DR_Chimp[[cell]], majortype_genes_DR_Chimp[[cell_name_list[[cell]]]])), 2)),
                                              cell, cell_name_list[[cell]], "DOWN", "Chimp"))


      counts      <- data.frame(rbind(c(-as.double(gene_proportion_table[gene_proportion_table$...1==cell, "Chimp.Specific.DOWN.Proportion"]), "Chimp", "DOWN"),
                                      c(-as.double(gene_proportion_table[gene_proportion_table$...1==cell, "Human.Specific.DOWN.Proportion"]), "Human", "DOWN"),
                                      c(as.double(gene_proportion_table[gene_proportion_table$...1==cell, "Chimp.Specific.UP.Proportion"]), "Chimp", "UP"),
                                      c(as.double(gene_proportion_table[gene_proportion_table$...1==cell, "Human.Specific.UP.Proportion"]), "Human", "UP")))

      counts$Cell <- cell

      all_counts  <- rbind(all_counts, counts)


    }

    df_subtype_overlap <- as.data.frame(rbind(sub_type_overlap_list_UR_HUMAN, sub_type_overlap_list_DR_HUMAN,
                                              sub_type_overlap_list_UR_CHIMP, sub_type_overlap_list_DR_CHIMP))


    all_counts$Study <- regions[[study]]

    colnames(all_counts) <- c("Proportion", "Species", "Regulation", "CellType", "Study")
    colnames(df_subtype_overlap) <- c("Overlap", "CellType", "Major_CellType", "Regulation", "Species")
    #all_counts <- all_counts[all_counts$CellType %in% neuron_selector, ]

    df_all_counts            <- all_counts
    df_all_counts$Proportion <- as.numeric(df_all_counts$Proportion)
    df_all_counts$Species    <- factor(df_all_counts$Species, levels = c("Chimp", "Human"), ordered = TRUE)

    df_all_counts$Regulation <- factor(df_all_counts$Regulation, levels = c("UP", "DOWN"))
    df_all_counts$CellType   <- factor(df_all_counts$CellType)

    #df_all_counts          <- df_all_counts[-c(4)]
    df_all_counts$Spec_Reg   <- paste0(df_all_counts$Species, "-", df_all_counts$Regulation)
    df_all_counts$Spec_Reg   <- factor(df_all_counts$Spec_Reg, levels = c("Human-UP", "Chimp-UP", "Human-DOWN", "Chimp-DOWN"  ))

    df_merged_bar_plot <- merge(df_all_counts, df_subtype_overlap, by = c("CellType", "Regulation", "Species"))
    study_wise_subtype_df <- rbind(study_wise_subtype_df, df_merged_bar_plot)
    study_wise_subtype_df$Overlap <- as.numeric(study_wise_subtype_df$Overlap)

  }

  Neuron_wise_df <- rbind(Neuron_wise_df, study_wise_subtype_df)

}


```

```{r}

saveRDS(Neuron_wise_df, "../../Visualization_data/Figure S17-18/Neuron_wise_df_proportion.rds")

```

