---
title: "Figure 1 - stacked Gene Proportions"
---

# IMPORT RELEVANT LIBARIES

```{r}
suppressMessages(suppressWarnings(library(ggplot2)))
suppressMessages(suppressWarnings(library(readxl)))
suppressWarnings(suppressMessages(library(gridExtra)))
suppressWarnings(suppressMessages(library(ggpubr)))
suppressWarnings(suppressMessages(library(grid)))
suppressMessages(suppressWarnings(library(stringr)))
suppressWarnings(suppressMessages(library(dplyr)))

```

# Initialize helper variables

```{r}

studies             <- c("Caglayan", "Ma")
cellnames           <- c("Astro", "Excite", "Inhibit", "Microglia", "Oligo", "OPC")
cellfullnames       <- c("Astrocyte", "Excitatory Neuron", "Inhibitory Neuron", "Microglia", "Oligodendrocyte", "OPC")

                       
regions             <- c("PCC", "dlPFC")

names(regions)      <- studies
names(cellfullnames)    <- cellnames
```


```{r}
geom_bar_width = 0.6
geom_bar_alpha_prop    = 0.8
geom_bar_alpha_overlap = 0.2
geom_errorbar_width = 0.15
geom_errorbar_dodge = 0.6
save_flag <- 0

Neuron_wise_df <- readRDS("Checkpoints/Figure 1/Neuron_wise_df_proportion.rds")

for (Neuron_type in c("Excite", "Inhibit")){
  
  neuron_df <- Neuron_wise_df[Neuron_wise_df$Major_CellType == Neuron_type, ]
  
  p     <- list()
  count <- 1
  
  for (study in studies){ 
    
    cell_count_studies <- read_excel("../Gene_List_results/Cell counts from both studies.xlsx", sheet = regions[[study]])
    cell_count_studies <- cell_count_studies[cell_count_studies$...2 %in% unique(neuron_df$CellType), ]
    
    plot_df    <- neuron_df[neuron_df$Study == regions[[study]], ]
    plot_df$CellType <- factor(plot_df$CellType, levels = unique(plot_df$CellType))
    
    # up regulated correlation plot between ratio and overlapping gene counts
    
    up_regulated_plot              <- plot_df[plot_df$Regulation == "UP", ]
    cell_count_studies             <- cell_count_studies[, c("...2", "hc_ratio")]
    colnames(cell_count_studies)   <- c("CellType", "hc_ratio")
    up_regulated_merged            <- merge(up_regulated_plot, cell_count_studies, by = "CellType")
    up_regulated_merged_difference <- up_regulated_merged %>% group_by(CellType) %>% summarise(Difference = diff(Proportion))
    up_regulated_difference_vs_ratio <- merge(up_regulated_merged_difference, up_regulated_merged, by = "CellType") 
    up_regulated_difference_vs_ratio <- up_regulated_difference_vs_ratio[, c("Difference", "hc_ratio")]
    up_regulated_difference_vs_ratio <- up_regulated_difference_vs_ratio[!duplicated(up_regulated_difference_vs_ratio), ]
    
    down_regulated_plot              <- plot_df[plot_df$Regulation == "DOWN", ]
    down_regulated_plot$Proportion   <- abs(down_regulated_plot$Proportion)
    down_regulated_merged            <- merge(down_regulated_plot, cell_count_studies, by = "CellType")
    down_regulated_merged_difference <- down_regulated_merged %>% group_by(CellType) %>% summarise(Difference = diff(Proportion))
    down_regulated_difference_vs_ratio <- merge(down_regulated_merged_difference, down_regulated_merged, by = "CellType")
    down_regulated_difference_vs_ratio <- down_regulated_difference_vs_ratio[, c("Difference", "hc_ratio")]
    down_regulated_difference_vs_ratio <- down_regulated_difference_vs_ratio[!duplicated(down_regulated_difference_vs_ratio), ]
    
    p[[count]] <- ggplot(plot_df, aes(CellType, fill = Spec_Reg))                                                          +   
                  geom_bar(data = plot_df, aes(y = Proportion), stat = "identity", position = "dodge", 
                           width = geom_bar_width, alpha=geom_bar_alpha_prop, color = "black")                             +
                  scale_fill_manual(values=list( "#0fbabd", "#bc131f", "#21675e", "#8c1044"))                              +
                  #geom_text(aes(label=Study, x = 1, y = 4), position=position_dodge(width=0.9), vjust=-1.0, size=5)       +
                  geom_hline(yintercept = 0,colour = "black")                                                              +
                  ylim(c(-4.5,  4.5)) +
                  theme(panel.grid.major = element_blank(), 
                        panel.grid.minor = element_blank(),                                                                                   
                        panel.background = element_blank(), 
                        axis.title.x =  element_blank(), 
                        axis.title.y = element_blank(), 
                        axis.line = element_line(colour = "black"),
                        axis.text.x=element_text(size=16, angle = 45, vjust = 1, hjust = 1),
                        axis.text=element_text(size=16)) +
                        scale_x_discrete(labels = function(x) str_wrap(x, width = 10), drop = FALSE)                      
    
    count <- count + 1
  }

  g <- ggarrange(plotlist = p, nrow=2, ncol = 1, common.legend = TRUE, legend="bottom")

  g <- annotate_figure(g, top = text_grob("Proportions of DEGs in considered Genes in both studies", color = "black", face = "bold", size = 20, y = 0.5))

  if  (save_flag == 1){
      ggsave(filename = paste0("Figures/Figure 1/Figure 1 - Subtype overlap counts_V4", study, "_", Neuron_type,"_proportion_stat_sig_subtypes.jpg"), plot = g, device = "jpeg",
          width=8.5, height=11, dpi=300)
    
  }

}

```

```{r}
cell_count_studies_PCC <- read_excel("../Gene_List_results/Cell counts from both studies.xlsx", sheet = "PCC")
cell_count_studies_dlPFC <- read_excel("../Gene_List_results/Cell counts from both studies.xlsx", sheet = "dlPFC")
```


<!-- ```{r} -->
<!-- geom_bar_width = 0.6 -->
<!-- geom_bar_alpha = 0.8 -->
<!-- geom_errorbar_width = 0.15 -->
<!-- geom_errorbar_dodge = 0.6 -->

<!-- Neuron_type <- "Excite" -->

<!-- p     <- list() -->
<!-- count <- 1 -->

<!-- Neuron_wise_df <- c() -->

<!-- for (Neuron_type in c("Excite", "Inhibit")){ -->

<!--   study_wise_subtype_df <- c() -->
<!--   for (study in studies){ -->

<!--     gene_proportion_table <- read_excel(paste0("Source Files/Figure 1/", study, "_gene_table_prefiltering.xlsx")) -->
<!--     local_cell_names            <- gene_proportion_table$...1 -->
<!--     cell_name_hash              <- readRDS(paste0("Checkpoints/Figure 1/", study, "_cell_name_hash.rds")) -->
<!--     cell_name_list              <- as.list(cell_name_hash) -->

<!--     neuron_selector             <- names(cell_name_list[cell_name_list==Neuron_type]) -->

<!--     subtype_genes_UR_Human         <- readRDS(paste0("../Gene_List_results/", study, "/", study, "0.05_original_HUMAN_URGenes.rds")) -->
<!--     subtype_genes_DR_Human         <- readRDS(paste0("../Gene_List_results/", study, "/", study, "0.05_original_HUMAN_DRGenes.rds")) -->

<!--     subtype_genes_UR_Chimp         <- readRDS(paste0("../Gene_List_results/", study, "/", study, "0.05_original_CHIMP_URGenes.rds")) -->
<!--     subtype_genes_DR_Chimp         <- readRDS(paste0("../Gene_List_results/", study, "/", study, "0.05_original_CHIMP_DRGenes.rds")) -->

<!--     majortype_genes_UR_Human               <- readRDS(paste0("../../Visualization - cellbender processed data - 018/Gene_List_results/", -->
<!--                                                              study, "/", study, "0.05_original_HUMAN_URGenes.rds")) -->
<!--     majortype_genes_DR_Human               <- readRDS(paste0("../../Visualization - cellbender processed data - 018/Gene_List_results/", -->
<!--                                                              study, "/", study, "0.05_original_HUMAN_DRGenes.rds")) -->

<!--     majortype_genes_UR_Chimp               <- readRDS(paste0("../../Visualization - cellbender processed data - 018/Gene_List_results/", -->
<!--                                                              study, "/", study, "0.05_original_CHIMP_URGenes.rds")) -->
<!--     majortype_genes_DR_Chimp               <- readRDS(paste0("../../Visualization - cellbender processed data - 018/Gene_List_results/", -->
<!--                                                              study, "/", study, "0.05_original_CHIMP_DRGenes.rds")) -->

<!--     sub_type_overlap_list_UR_HUMAN <- c() -->
<!--     sub_type_overlap_list_DR_HUMAN <- c() -->
<!--     sub_type_overlap_list_UR_CHIMP <- c() -->
<!--     sub_type_overlap_list_DR_CHIMP <- c() -->

<!--     all_counts <- c() -->

<!--     for (cell in neuron_selector){ -->

<!--       sub_type_overlap_list_UR_HUMAN <- rbind(sub_type_overlap_list_UR_HUMAN, -->
<!--                                               c(as.numeric(round(length(intersect(subtype_genes_UR_Human[[cell]], majortype_genes_UR_Human[[cell_name_list[[cell]]]])), 2)), -->
<!--                                               cell, cell_name_list[[cell]], "UP", "Human")) -->

<!--       sub_type_overlap_list_DR_HUMAN <- rbind(sub_type_overlap_list_DR_HUMAN, -->
<!--                                               c(as.numeric(-round(length(intersect(subtype_genes_DR_Human[[cell]], majortype_genes_DR_Human[[cell_name_list[[cell]]]])), 2)), -->
<!--                                               cell, cell_name_list[[cell]], "DOWN", "Human")) -->

<!--       sub_type_overlap_list_UR_CHIMP <- rbind(sub_type_overlap_list_UR_CHIMP, -->
<!--                                               c(as.numeric(round(length(intersect(subtype_genes_UR_Chimp[[cell]], majortype_genes_UR_Chimp[[cell_name_list[[cell]]]])), 2)), -->
<!--                                               cell, cell_name_list[[cell]], "UP", "Chimp")) -->

<!--       sub_type_overlap_list_DR_CHIMP <- rbind(sub_type_overlap_list_DR_CHIMP, -->
<!--                                               c(as.numeric(-round(length(intersect(subtype_genes_DR_Chimp[[cell]], majortype_genes_DR_Chimp[[cell_name_list[[cell]]]])), 2)), -->
<!--                                               cell, cell_name_list[[cell]], "DOWN", "Chimp")) -->


<!--       counts      <- data.frame(rbind(c(-as.double(gene_proportion_table[gene_proportion_table$...1==cell, "Chimp.Specific.DOWN.Proportion"]), "Chimp", "DOWN"), -->
<!--                                       c(-as.double(gene_proportion_table[gene_proportion_table$...1==cell, "Human.Specific.DOWN.Proportion"]), "Human", "DOWN"), -->
<!--                                       c(as.double(gene_proportion_table[gene_proportion_table$...1==cell, "Chimp.Specific.UP.Proportion"]), "Chimp", "UP"), -->
<!--                                       c(as.double(gene_proportion_table[gene_proportion_table$...1==cell, "Human.Specific.UP.Proportion"]), "Human", "UP"))) -->

<!--       counts$Cell <- cell -->

<!--       all_counts  <- rbind(all_counts, counts) -->


<!--     } -->

<!--     df_subtype_overlap <- as.data.frame(rbind(sub_type_overlap_list_UR_HUMAN, sub_type_overlap_list_DR_HUMAN, -->
<!--                                               sub_type_overlap_list_UR_CHIMP, sub_type_overlap_list_DR_CHIMP)) -->


<!--     all_counts$Study <- regions[[study]] -->

<!--     colnames(all_counts) <- c("Proportion", "Species", "Regulation", "CellType", "Study") -->
<!--     colnames(df_subtype_overlap) <- c("Overlap", "CellType", "Major_CellType", "Regulation", "Species") -->
<!--     #all_counts <- all_counts[all_counts$CellType %in% neuron_selector, ] -->

<!--     df_all_counts            <- all_counts -->
<!--     df_all_counts$Proportion <- as.numeric(df_all_counts$Proportion) -->
<!--     df_all_counts$Species    <- factor(df_all_counts$Species, levels = c("Chimp", "Human"), ordered = TRUE) -->

<!--     df_all_counts$Regulation <- factor(df_all_counts$Regulation, levels = c("UP", "DOWN")) -->
<!--     df_all_counts$CellType   <- factor(df_all_counts$CellType) -->

<!--     #df_all_counts          <- df_all_counts[-c(4)] -->
<!--     df_all_counts$Spec_Reg   <- paste0(df_all_counts$Species, "-", df_all_counts$Regulation) -->
<!--     df_all_counts$Spec_Reg   <- factor(df_all_counts$Spec_Reg, levels = c("Human-UP", "Chimp-UP", "Human-DOWN", "Chimp-DOWN"  )) -->

<!--     df_merged_bar_plot <- merge(df_all_counts, df_subtype_overlap, by = c("CellType", "Regulation", "Species")) -->
<!--     study_wise_subtype_df <- rbind(study_wise_subtype_df, df_merged_bar_plot) -->
<!--     study_wise_subtype_df$Overlap <- as.numeric(study_wise_subtype_df$Overlap) -->

<!--   } -->

<!--   Neuron_wise_df <- rbind(Neuron_wise_df, study_wise_subtype_df) -->

<!-- } -->

<!-- saveRDS(Neuron_wise_df, "Checkpoints/Figure 1/Neuron_wise_df_proportion.rds") -->

<!-- ``` -->

