
```{r}

source("../../Baseline/Figure S19 Baseline - Visualization all subtypes.R")

```

```{r}
lineplot_human_UR_list    <- readRDS(paste0("../../Visualization_data/Figure S19/cell_type_list_combo_V4.rds"))

for (cellname in cellnames_of_interest[1]){
  
  current_line_plot_df                                   <- lineplot_human_UR_list[[cellname]][[1]]
  current_line_plot_df$`#Subtypes`                       <- as.numeric(current_line_plot_df$`#Subtypes`)
  current_line_plot_df$comb_names                        <- rownames(current_line_plot_df)
  current_line_plot_df$`Sub type and cell specific DEGs` <- as.numeric(current_line_plot_df$`Sub type and cell specific DEGs`)
  
  df_prime          <- as.data.frame(lapply(current_line_plot_df, function(x) if(is.character(x)) as.numeric(as.character(x)) else x))
  
  df_prime$Rowsum <- rowSums(df_prime[, c("Cell.specific.DEGs.present.in.both.studies", "Cell.specific.subtype.DEGs.present.in.excitatory.neuron.shared.DEGs", "Shared.DEGs.present.in.both.studies", "Shared.subtype.DEGs.present.in.excitatory.neuron.cell.type.DEGs", "Sub.type.and.cell.specific.DEGs", "Sub.type.and.shared.DEGs")])
  
  mean_data         <- df_prime %>% group_by(X.Subtypes) %>% summarise(mean_value   = mean(Rowsum))
  
  quadratic_model <- lm(mean_value ~ poly(X.Subtypes, 2, raw = TRUE), data = mean_data)
    # Extract coefficients
  coefficients <- coef(quadratic_model)
  
  # Calculate the second derivative (2 * a from ax^2 + bx + c)
  second_derivative <- 2 * coefficients[3]
  
  summary_model <- summary(quadratic_model)
  
  print(summary_model)
  
  r_squared <- summary_model$r.squared

  
  print(mean_data)
  p <- ggplot(df_prime, aes(x = X.Subtypes, y = Rowsum))     + 
       ggdist::stat_halfeye(adjust = .5, width = 0.9, .width = 0, justification = -.3, point_interval = NULL, fill= "tomato")   +
       geom_point(size = 1.5, alpha = .2, position = position_jitter(seed = 1, width = .1), color = "tomato")                   +
       xlab("")                                             +
       ylab("")                                             +
       #ylim(c(-4, 1))                                      +
       #ggtitle(subtitle = Cell)                            +
       theme_bw()                                           +
       geom_point(data = mean_data,   aes(x = X.Subtypes, y = mean_value), color = "black", size = 6, shape = 18)    + 
       geom_smooth(data = mean_data, aes(x = X.Subtypes, y = mean_value), method = "lm", formula = y ~ poly(x, 2, raw = TRUE), se = FALSE, color = "blue") +
       theme(axis.text.y  = element_blank(),
             axis.text.x  = element_blank(),
             axis.ticks.y = element_blank(),
             axis.ticks.x = element_blank(),
             plot.title = element_text(hjust = 0.5)) 

  # ggsave(filename = paste0("../../Figures/Version 5/all_subtype_combinations/", cellname, "all_subtypes_subset_combination_scatter_plot_blank_Version5_re.jpg"), plot = p, device = "jpeg",
  #           width=7, height=7, dpi=300)

  p
  
}


```
