---
title: "Prepares the checkpoints and visualization data for Figures S1-S3"
output: 
editor_options: 
  chunk_output_type: inline
---

```{r}

source("../../Baseline/Figure 1 Baseline.R")

```



# Recalculating aggregate cell count numbers

```{r}

for (study in study_results){

  chimp_aggregate_study_cell_count_hash   <- list()
  human_aggregate_study_cell_count_hash   <- list()
  macaque_aggregate_study_cell_count_hash <- list()


  cell_number_file <- read_excel(paste0(folder_name , study, "/", study, "_MajorCellTypes.xlsx"))
  colnames(cell_number_file) <- c("cell_type", "chimp", "macaque", "human")


  for (cell_type in cell_number_file$cell_type[1:6]){

    chimp_aggregate_study_cell_count_hash[[cell_type]] <- c(chimp_aggregate_study_cell_count_hash[[cell_type]], as.numeric(round(cell_number_file[cell_number_file$cell_type == cell_type, "chimp"]*cell_number_file[cell_number_file$cell_type == "TOTAL", "chimp"]/100)[1, 1]))

    human_aggregate_study_cell_count_hash[[cell_type]] <- c(human_aggregate_study_cell_count_hash[[cell_type]], round(cell_number_file[cell_number_file$cell_type == cell_type, "human"]*cell_number_file[cell_number_file$cell_type == "TOTAL", "human"]/100)[1, 1])

    macaque_aggregate_study_cell_count_hash[[cell_type]] <- c(macaque_aggregate_study_cell_count_hash[[cell_type]], round(cell_number_file[cell_number_file$cell_type == cell_type, "human"]*cell_number_file[cell_number_file$cell_type == "TOTAL", "macaque"]/100)[1, 1])

  }

  names(chimp_aggregate_study_cell_count_hash) <- cell_types
  names(human_aggregate_study_cell_count_hash) <- cell_types
  names(macaque_aggregate_study_cell_count_hash) <- cell_types
  
  # saveRDS(chimp_aggregate_study_cell_count_hash,   paste0("../../Visualization_data/Figure 1/checkpoints/", study, "_chimp_numbers.rds"))
  # saveRDS(human_aggregate_study_cell_count_hash,   paste0("../../Visualization_data/Figure 1/checkpoints/", study, "_human_numbers.rds"))
  # saveRDS(macaque_aggregate_study_cell_count_hash, paste0("../../Visualization_data/Figure 1/checkpoints/", study, "_macaque_numbers.rds"))
  # 
}
```

```{r}
DESeq_chimp_DR <- list()
DESeq_chimp_UR <- list()
DESeq_human_DR <- list()
DESeq_human_UR <- list()

p_value_UP     <- list()
p_value_DOWN   <- list()

considered_list <- list()

chimp_boot_DR          <- readRDS(paste0(bootstrap_results_path, "consolidated_chimp_DR.rds"))
chimp_boot_UR          <- readRDS(paste0(bootstrap_results_path, "consolidated_chimp_UR.rds"))
human_boot_DR          <- readRDS(paste0(bootstrap_results_path, "consolidated_human_DR.rds"))
human_boot_UR          <- readRDS(paste0(bootstrap_results_path, "consolidated_human_UR.rds"))

considered_boot        <- readRDS(paste0(bootstrap_results_path, "consolidated_considered.rds"))

for (study in c("Caglayan", "Ma")){
  
  DESeq_chimp_DR_cell_type <- list()
  DESeq_chimp_UR_cell_type <- list()
  DESeq_human_DR_cell_type <- list()
  DESeq_human_UR_cell_type <- list()
  
  p_value_UP_cell_type     <- list()
  p_value_DOWN_cell_type   <- list()
  
  considered_boot_cell_type  <- list()
  
  for (cell_type in cell_number_file$cell_type[1:6]){

    DESeq_chimp_DR_cell_type[[cell_type]] <- quantile(unlist(chimp_boot_DR[[study]][[cell_type]]),   probs = c(.025, .975))
    DESeq_chimp_UR_cell_type[[cell_type]] <- quantile(unlist(chimp_boot_UR[[study]][[cell_type]]),   probs = c(.025, .975))
    DESeq_human_DR_cell_type[[cell_type]] <- quantile(unlist(human_boot_DR[[study]][[cell_type]]),   probs = c(.025, .975))
    DESeq_human_UR_cell_type[[cell_type]] <- quantile(unlist(human_boot_UR[[study]][[cell_type]]),   probs = c(.025, .975))
    
    considered_boot_cell_type[[cell_type]]  <- quantile(unlist(considered_boot[[study]][[cell_type]]),   probs = c(.025, .975))
  
  }
  
DESeq_chimp_DR[[study]] <- DESeq_chimp_DR_cell_type
DESeq_chimp_UR[[study]] <- DESeq_chimp_UR_cell_type
DESeq_human_DR[[study]] <- DESeq_human_DR_cell_type
DESeq_human_UR[[study]] <- DESeq_human_UR_cell_type

considered_list[[study]] <- considered_boot_cell_type
}

```

```{r}
DESeq_chimp_DR_proportion <- list()
DESeq_chimp_UR_proportion <- list()
DESeq_human_DR_proportion <- list()
DESeq_human_UR_proportion <- list()

DESeq_chimp_UR_proportion_ratio <- list()
DESeq_chimp_DR_proportion_ratio <- list()

chimp_boot_DR          <- readRDS(paste0(bootstrap_results_path, "consolidated_chimp_DR.rds"))
chimp_boot_UR          <- readRDS(paste0(bootstrap_results_path, "consolidated_chimp_UR.rds"))
human_boot_DR          <- readRDS(paste0(bootstrap_results_path, "consolidated_human_DR.rds"))
human_boot_UR          <- readRDS(paste0(bootstrap_results_path, "consolidated_human_UR.rds"))

considered_boot        <- readRDS(paste0(bootstrap_results_path, "consolidated_considered.rds"))

for (study in c("Caglayan", "Ma")){
  
  DESeq_chimp_DR_cell_type <- list()
  DESeq_chimp_UR_cell_type <- list()
  DESeq_human_DR_cell_type <- list()
  DESeq_human_UR_cell_type <- list()
  
  DESeq_chimp_UR_cell_type_ratio <- list()
  DESeq_chimp_DR_cell_type_ratio <- list()
  
  p_value_UP_cell_type     <- list()
  p_value_DOWN_cell_type   <- list()
  
  for (cell_type in cell_number_file$cell_type[1:6]){

    DESeq_chimp_DR_cell_type[[cell_type]] <- quantile(round(100*unlist(chimp_boot_DR[[study]][[cell_type]])/unlist(considered_boot[[study]][[cell_type]]), 2),   probs = c(.025, .975))
    DESeq_chimp_UR_cell_type[[cell_type]] <- quantile(round(100*unlist(chimp_boot_UR[[study]][[cell_type]])/unlist(considered_boot[[study]][[cell_type]]), 2),   probs = c(.025, .975))
    DESeq_human_DR_cell_type[[cell_type]] <- quantile(round(100*unlist(human_boot_DR[[study]][[cell_type]])/unlist(considered_boot[[study]][[cell_type]]), 2),   probs = c(.025, .975))
    DESeq_human_UR_cell_type[[cell_type]] <- quantile(round(100*unlist(human_boot_UR[[study]][[cell_type]])/unlist(considered_boot[[study]][[cell_type]]), 2),   probs = c(.025, .975))
    
    DESeq_chimp_UR_cell_type_ratio[[cell_type]] <- quantile(round(unlist(human_boot_UR[[study]][[cell_type]])/unlist(chimp_boot_UR[[study]][[cell_type]]), 2),   probs = c(.025, .975))
    DESeq_chimp_DR_cell_type_ratio[[cell_type]] <- quantile(round(unlist(human_boot_DR[[study]][[cell_type]])/unlist(chimp_boot_DR[[study]][[cell_type]]), 2),   probs = c(.025, .975))

  
    p_value_DOWN_cell_type_data <- ks.test(unlist(chimp_boot_DR[[study]][[cell_type]])/unlist(considered_boot[[study]][[cell_type]]), unlist(human_boot_DR[[study]][[cell_type]])/unlist(considered_boot[[study]][[cell_type]]))
    p_value_UP_cell_type_data   <- ks.test(unlist(chimp_boot_UR[[study]][[cell_type]])/unlist(considered_boot[[study]][[cell_type]]), unlist(human_boot_UR[[study]][[cell_type]])/unlist(considered_boot[[study]][[cell_type]]))
    
    p_value_DOWN_cell_type[[cell_type]] <- p_value_DOWN_cell_type_data$p.value
    p_value_UP_cell_type[[cell_type]]   <- p_value_UP_cell_type_data$p.value
    
    considered_boot_cell_type[[cell_type]] <- quantile(unlist(considered_boot[[study]][[cell_type]]),   probs = c(.025, .975))
  }
  
DESeq_chimp_DR_proportion[[study]] <- DESeq_chimp_DR_cell_type
DESeq_chimp_UR_proportion[[study]] <- DESeq_chimp_UR_cell_type
DESeq_human_DR_proportion[[study]] <- DESeq_human_DR_cell_type
DESeq_human_UR_proportion[[study]] <- DESeq_human_UR_cell_type

DESeq_chimp_UR_proportion_ratio[[study]] <- DESeq_chimp_UR_cell_type_ratio
DESeq_chimp_DR_proportion_ratio[[study]] <- DESeq_chimp_DR_cell_type_ratio

p_value_DOWN[[study]] <- p_value_DOWN_cell_type
p_value_UP[[study]]   <- p_value_UP_cell_type

  
}
```

```{r}

for (study in study_results){
   
  chimp_down_regulated          <- readRDS(paste0(folder_name, study, "/", study, FDR, "_original_CHIMP_DRGene_numbers.rds"))
  human_down_regulated          <- readRDS(paste0(folder_name, study, "/", study, FDR, "_original_HUMAN_DRGene_numbers.rds"))
  chimp_up_regulated            <- readRDS(paste0(folder_name, study, "/", study, FDR, "_original_CHIMP_URGene_numbers.rds"))
  human_up_regulated            <- readRDS(paste0(folder_name, study, "/", study, FDR, "_original_HUMAN_URGene_numbers.rds"))
  considered_Genes              <- readRDS(paste0(folder_name, study, "/", study, FDR, "_three_species_considered_Gene_Number.rds"))
  
  gene_proportion_table         <- c()

  for (key in names(chimp_up_regulated)){
    
        gene_proportion_table <- rbind(gene_proportion_table, c(human_up_regulated[[key]],    paste0("(", DESeq_human_UR[[study]][[key]][1], ",", DESeq_human_UR[[study]][[key]][2], ")"),
                                                            chimp_up_regulated[[key]],    paste0("(", DESeq_chimp_UR[[study]][[key]][1], ",", DESeq_chimp_UR[[study]][[key]][2], ")"),
                                                            human_down_regulated[[key]],  paste0("(", DESeq_human_DR[[study]][[key]][1], ",", DESeq_human_DR[[study]][[key]][2], ")"),
                                                            chimp_down_regulated[[key]],  paste0("(", DESeq_chimp_DR[[study]][[key]][1], ",", DESeq_chimp_DR[[study]][[key]][2], ")"),
                                                            considered_Genes[[key]],      paste0("(", considered_list[[study]][[key]][1], ",", considered_list[[study]][[key]][2], ")"),
                                                            round(100*human_up_regulated[[key]]/considered_Genes[[key]], 2),    DESeq_human_UR_proportion[[study]][[key]][1],  DESeq_human_UR_proportion[[study]][[key]][2],
                                                            round(100*chimp_up_regulated[[key]]/considered_Genes[[key]], 2),    DESeq_chimp_UR_proportion[[study]][[key]][1],  DESeq_chimp_UR_proportion[[study]][[key]][2],         p_value_UP[[study]][[key]],
                                                            round(100*human_down_regulated[[key]]/considered_Genes[[key]], 2),  DESeq_human_DR_proportion[[study]][[key]][1],  DESeq_human_DR_proportion[[study]][[key]][2],         
                                                            round(100*chimp_down_regulated[[key]]/considered_Genes[[key]], 2),  DESeq_chimp_DR_proportion[[study]][[key]][1],  DESeq_chimp_DR_proportion[[study]][[key]][2],         p_value_DOWN[[study]][[key]],
                                                            round(human_up_regulated[[key]]/chimp_up_regulated[[key]], 2),      DESeq_chimp_UR_proportion_ratio[[study]][[key]][1],  DESeq_chimp_UR_proportion_ratio[[study]][[key]][2],
                                                            round(human_down_regulated[[key]]/chimp_down_regulated[[key]], 2),  DESeq_chimp_DR_proportion_ratio[[study]][[key]][1],  DESeq_chimp_DR_proportion_ratio[[study]][[key]][2]))
        
  }
    


colnames(gene_proportion_table) <- c("Human Specific UP",   "95 % bootstrapped interval",
                                       "Chimp Specific UP",   "95 % bootstrapped interval",
                                       "Human Specific DOWN", "95 % bootstrapped interval",
                                       "Chimp Specific DOWN", "95 % bootstrapped interval",
                                       "Considered Genes",    "95 % bootstrapped interval",
                                       "Human Specific UP Proportion",    "95 % bootstrapped interval HU LOW", "95 % bootstrapped interval HU HIGH",
                                       "Chimp Specific UP Proportion",    "95 % bootstrapped interval CU LOW", "95 % bootstrapped interval CU HIGH", "KS - p-value",
                                       "Human Specific DOWN Proportion",  "95 % bootstrapped interval HD LOW", "95 % bootstrapped interval HD HIGH",
                                       "Chimp Specific DOWN Proportion",  "95 % bootstrapped interval CD LOW", "95 % bootstrapped interval CD HIGH", "KS - p-value",
                                       "Up - Ratio", "95 % bootstrapped interval UR - LOW", "95 % bootstrapped interval UR - HIGH",
                                       "Down - Ratio", "95 % bootstrapped interval DR - LOW", "95 % bootstrapped interval DR - HIGH")
  
  rownames(gene_proportion_table) <- cell_types

  gene_proportion_table <- cbind(" "=rownames(gene_proportion_table), gene_proportion_table)


  print(gene_proportion_table)
  gene_proportion_table <- as.data.frame(gene_proportion_table)
  write.xlsx(gene_proportion_table, paste0(gene_table_path, study, "_gene_table_Figure_1.xlsx"))
  
}
```


```{r}
# Example sorted lists with repetitions
list1 <- c(1, 2, 2, 3, 3, 3, 4)
list2 <- c(2, 3, 3, 5, 6)

# Find common elements
common_elements <- intersect(list1, list2)

# Count the occurrences in both lists
count_list1 <- table(list1)
count_list2 <- table(list2)

# Initialize the overlap count
overlap_count <- 0

# Sum the minimum counts for each common element
for (element in common_elements) {
  overlap_count <- overlap_count + min(count_list1[element], count_list2[element])
}

# Print the overlap count
print(overlap_count)

study_df <- c()

for (study in c("Caglayan", "Ma")){
  
  for (cell_type in cell_number_file$cell_type[6]){

    DR_list1 <- unlist(chimp_boot_DR[[study]][[cell_type]])
    DR_list2 <- unlist(human_boot_DR[[study]][[cell_type]])
    
    DR_common_elements <- intersect(DR_list1, DR_list2)
    
    count_DR_list1 <- table(DR_list1)
    count_DR_list2 <- table(DR_list2)
    
    DR_overlap_count <- 0

    # Sum the minimum counts for each common element
    for (element in DR_common_elements) {
      DR_overlap_count <- DR_overlap_count + min(count_DR_list1[as.character(element)], 
                                                 count_DR_list2[as.character(element)])
    }
    
    UR_list1 <- unlist(chimp_boot_UR[[study]][[cell_type]])
    UR_list2 <- unlist(human_boot_UR[[study]][[cell_type]])
    
    UR_common_elements <- intersect(UR_list1, UR_list2)
    
    count_UR_list1 <- table(UR_list1)
    count_UR_list2 <- table(UR_list2)
    
    UR_overlap_count <- 0
    
    # Sum the minimum counts for each common element
    for (element in UR_common_elements) {
      UR_overlap_count <- UR_overlap_count + min(count_UR_list1[as.character(element)], 
                                                 count_UR_list2[as.character(element)])
    }
    
    study_df <- rbind(study_df,   c(as.numeric(UR_overlap_count)/10000, 
                                   as.numeric(DR_overlap_count)/10000,
                                   cell_type,
                                   study))

  }

}

study_df <- as.data.frame(study_df)
colnames(study_df) <- c("Up regulation", "Down regulation",
                        "Cell Type", "Study")

study_df$`Up regulation` <- as.numeric(study_df$`Up regulation`)
study_df$`Down regulation` <- as.numeric(study_df$`Down regulation`)


```

```{r}
write.xlsx()
```

