```{r}

source("../../Baseline/Figure 3.1 Baseline.R")

```

# Mapping by species to HAR values - V1

```{r}

plot_type <- "specificity_values"
stat_pos  <- 1.1
p         <- list()
count     <- 1

for (spec in species_type[1]){
  
  cell_plot_list  <- list()
  cell_plot_count <- 1
  
  stat.test_DEG            <- stats_data[[plot_type]]
  stat.test_DEG$y.position <- rep(stat_pos, dim(stat.test_DEG)[[1]])
  df                       <- barplot_data[[plot_type]]
  
  mean_calculation_df      <- df
  
  mean_data                <- mean_calculation_df %>% group_by(Cell, DEG, Region) %>% summarise(mean_value   = mean(specificity_values))
  median_data              <- mean_calculation_df %>% group_by(Cell, DEG, Region) %>% summarise(median_value = median(specificity_values))
  
  mean_data$Cell_Region    <- paste0(mean_data$Cell,   " ", mean_data$Region)
  median_data$Cell_Region  <- paste0(median_data$Cell, " ", median_data$Region)
  
  breaks <- c(0, 0.2, 0.4, 0.6, 0.8, 1)
  
  for (cell_region in cell_plot_order){
    
    plot_df          <- df[df$Cell_Region == cell_region, ]
    plot_df          <- plot_df[!duplicated(plot_df$Gene), ]
    
    plot_mean_data   <- mean_data[mean_data$Cell_Region == cell_region, ]
    plot_median_data <- median_data[median_data$Cell_Region == cell_region, ]
    
    plot_stat.test_DEG <- stat.test_DEG[stat.test_DEG$Cell_Region %in% cell_region, ]
    
    cell_plot_list[[cell_plot_count]] <- ggplot(plot_df, aes(x=DEG, y=specificity_values))                                                                        +
                                         ggdist::stat_halfeye(aes(fill=DEG), adjust = .5, width = 0.55, .width = 0, justification = -.3, point_interval = NULL)   +
                                         geom_point(aes(color=Expression), size = 1.5, alpha = .2, position = position_jitter(seed = 1, width = .1))              +
                                         geom_point(data = plot_mean_data,   aes(x = DEG, y = mean_value), color = "black", size = 6, shape = 18)                 +
                                         xlab("")                                             +
                                         ylab("")                                             +
                                         theme_bw()                                           +
                                         theme(axis.text.y  = element_text(),
                                               axis.text.x  = element_blank(),
                                               axis.ticks.y = element_blank(),
                                               axis.ticks.x = element_blank(),
                                               plot.title = element_text(hjust = 0.5),
                                               legend.position = "none")                                                         +
                                         add_pvalue(plot_stat.test_DEG, label = "{p.signif}", label.size = 6, tip.length = 0.01) +
                                         scale_fill_manual(values = c("DEG"="#0fbabd", "background"="skyblue"))                  +
                                         scale_color_gradient(low = "blue", high = "red")                                        +
                                         guides(fill=guide_legend(title="Type of Gene"))                                         +
                                         scale_y_continuous(limits = c(0, 1.2), breaks = breaks)                     
    
    #No shared levels found between `names(values)` of the manual scale and the data's colour values.
    
    cell_plot_list[[cell_plot_count]]
    
    cell_plot_count <- cell_plot_count + 1
    
  }
  
  cell_plot_arrange <- ggarrange(plotlist = cell_plot_list, nrow=2, ncol = 6, common.legend = FALSE)

  ggsave(filename = paste0("../../Figures/Figure 3/specificity_plot_YES_axis", spec, "_Violin_offlinedNdS.jpg"), plot = cell_plot_arrange, device = "jpeg",
         width=16, height=9, dpi=300)

  cell_plot_arrange
  count <- count + 1

}

```

